### ISSUE TITLE
Automated setup issue - Mono

### ISSUE THREAD

**Issue by Stady234** [michaelfdeberry/overseer#13]
$ chmod 744 ./overseer-linux-armv6.sh && sudo ./overseer-linux-armv6.sh

./overseer-linux-armv6.sh: 1: ./overseer-linux-armv6.sh: #!/bin/bash: not found
Installing Overseer...
Hit:1 http://archive.raspberrypi.org/debian stretch InRelease
Ign:2 http://ftp.debian.org/debian stretch InRelease
Hit:3 http://security.debian.org stretch/updates InRelease
Hit:4 http://ftp.debian.org/debian stretch-updates InRelease
Hit:5 http://ftp.debian.org/debian stretch Release
Reading package lists... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  mono-complete
0 upgraded, 1 newly installed, 0 to remove and 8 not upgraded.
Need to get 0 B/29.9 kB of archives.
After this operation, 60.4 kB of additional disk space will be used.
Selecting previously unselected package mono-complete.
(Reading database ... 137645 files and directories currently installed.)
Preparing to unpack .../mono-complete_4.6.2.7+dfsg-1_i386.deb ...
Unpacking mono-complete (4.6.2.7+dfsg-1) ...
Setting up mono-complete (4.6.2.7+dfsg-1) ...
Restart=on-failure
--2019-01-26 16:25:20--  https://github.com/michaelfdeberry/overseer/releases/download/1.0.0/overseer-linux-amrv6.zip
Resolving github.com (github.com)... 192.30.253.112, 192.30.253.113
Connecting to github.com (github.com)|192.30.253.112|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-01-26 16:25:20 ERROR 404: Not Found.

Overseer installation has completed.

**Comment by michaelfdeberry** [comment]
Retested both install scripts and updated the release page. If you have any additional problems with the install script please create a new issue.
