### ISSUE TITLE
Overseer Daemon (.Net Core) - Automated

### ISSUE THREAD

**Issue by Stady234** [michaelfdeberry/overseer#15]
overseer-linux-armv7.s 100%[===========================>]   1.88K  --.-KB/s    in 0s

2019-01-28 12:27:10 (36.5 MB/s) - ‘overseer-linux-armv7.sh’ saved [1920/1920]

pi@PiVM:~ $ chmod 744 ./overseer-linux-armv7.sh && sudo ./overseer-linux-armv7.sh
: not foundlinux-armv7.sh: 1: ./overseer-linux-armv7.sh: #!/bin/bash
: not foundlinux-armv7.sh: 2: ./overseer-linux-armv7.sh:
: not foundlinux-armv7.sh: 11: ./overseer-linux-armv7.sh:
Installing Overseer...
: not foundlinux-armv7.sh: 13: ./overseer-linux-armv7.sh:
E: Invalid operation update
: not foundlinux-armv7.sh: 16: ./overseer-linux-armv7.sh:
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package apt-transport-https
: not foundlinux-armv7.sh: 19: ./overseer-linux-armv7.sh:
./overseer-linux-armv7.sh: 59: ./overseer-linux-armv7.sh: Syntax error: end of file unexpected (expecting "fi")

**Comment by michaelfdeberry** [comment]
Closing this since it's the same issue as #14
