### ISSUE TITLE
Overseer Daemon (.Net Core) - Automated Install - Issues

### ISSUE THREAD

**Issue by Stady234** [michaelfdeberry/overseer#16]
Ran the automated script... no errors.
Setup the haproxy and added the line you updated...

Append the configuration below to the bottom of the file

> frontend overseer-public
>         bind *:80 v4v6
>         use_backend overseer
> 
> backend overseer
>         http-request set-header Host "localhost"  <-- tried with and without this line
>         server overseer1 localhost:9000
> 

Not able to see page either local on pi (chromium browser) or from network client.

Removed all of haproxy and reboot

Setup Nginx per instructions and made modification you said to remove.

Replace the contents of the file with the configuration below.

> 
> server {
>     listen                      80;
> 
>     location / {
>         proxy_pass              http://localhost:9000;
>         proxy_http_version      1.1;
>         proxy_cache_bypass      $http_upgrade;        
>         proxy_set_header        Upgrade $http_upgrade;
>         proxy_set_header        Connection keep-alive;
>         proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
>         proxy_set_header        X-Forwarded-Proto $scheme;
>         proxy_set_header        Host $host;      <-- tried with and without this line
>     }
> }
> 
> 

only receiving "502 Bad Gateway" both localhost, and clients via direct IP.

**Comment by michaelfdeberry** [comment]
The additional reverse proxy configuration shouldn't be needed for this version. 

From the error you are getting I am assuming the overseer service isn't running. Run `htop` and look for the Overseer.Daemon process. 

If it's not there try to start the process manually. To do this `cd` into the overseer directory and then execute `./Overseer.Daemon` 

If you get an error message please post it here. 

If it starts it's likely an issue with the service configuration. 

I believe you are using a VM. I suppose it is possible that the hardware target for your VM doesn't support the ARMv7 instructions which this version requires.

**Comment by michaelfdeberry** [comment]
I am not able to replicate any issues with the .Net Core version when running on compatible hardware. 

There is a new version, but I suspect you will likely have the same issue.
