### ISSUE TITLE
Printer Display Size Incorrect When Machines Are Hidden

### ISSUE THREAD

**Issue by tophattwaffle** [michaelfdeberry/overseer#19]
With hide idle machines, and hide disabled machines enabled, with a single printer active, the camera will only take up a small portion of the window unless focused by clicking on it.

![image](https://user-images.githubusercontent.com/6774125/53260333-d8b14000-3696-11e9-840f-fadbed1f9202.png)

![image](https://user-images.githubusercontent.com/6774125/53260353-e4046b80-3696-11e9-9f68-860e923fd24f.png)

With both of these settings off, the window displays all printers as expected.
![image](https://user-images.githubusercontent.com/6774125/53260372-f2528780-3696-11e9-9bf0-03692a3ec36a.png)

**Comment by michaelfdeberry** [comment]
I pushed a fix to the dev branch that will be included in the next release. That will probably be out this weekend when the sorting functionality is finished.

I guess a temporary fix would be resizing the browser window as that will trigger the code to resize the grid.

**Comment by tophattwaffle** [comment]
You're doing the lords work. Resizing works great for now.

**Comment by michaelfdeberry** [comment]
Resolved in 1.0.3
