### ISSUE TITLE
[Feature Request] Flip webcam view

### ISSUE THREAD

**Issue by taker218** [michaelfdeberry/overseer#30]
Would it be possible to add a setting that you can flip the webcam?

I have one webcam which is flipped horizontally in Octoprint.
So in overseer it is flipped upside down.

**Comment by michaelfdeberry** [comment]
Yes, I will make sure it's in the next release. 

I don't know how much time I will have to work on Overseer, but I hope to have a new version out either this weekend or the next.

**Comment by taker218** [comment]
Any news on the next release?

Or is there a way I could test the changes you made? I saw that you made some changes in the code regarding this topic.

**Comment by michaelfdeberry** [comment]
I discovered a few bugs that delayed the release, but I can potentially put a release out this evening

**Comment by michaelfdeberry** [comment]
I put out a release that adds this functionality. For now it just supports flipping the image, but I might add support for rotating at some point.

**Comment by taker218** [comment]
awesome, thanks for the release, will test it right away

**Comment by michaelfdeberry** [comment]
If you use overseer.live the changes my not be available immediately. 

I am going to close this, but if you find any problems please open a new issue.
