### ISSUE TITLE
Request - Show live gcode progress view if no webcam available?

### ISSUE THREAD

**Issue by digitalsanity** [michaelfdeberry/overseer#4]
If no webcam is available, can you show the gcode viewer tab of octoprint for that printer instead of the 'snow' effect?

**Comment by michaelfdeberry** [comment]
That was actually something that was going to be supported initially, but ended up being dropped.

A couple of the main issues are: 

1. Performance: The gcode file would need to be loaded for that to work and large gcode files can be problem. This is an issue for Octoprint, and it would only be rendering a gcode file for a single print. With Overseer there is potential that multiple gcode files could be rendered at once which could slow down or crash the browser.  

1. Compatibility: I suppose a long term goal is to support any printer with a web interface. Overseer currently supports the RepRap firmware in addition to Octoprint. There are plans to support printers connected with USB as well. This feature would only work with Octoprint when not printing from SD. 

Something I was thinking about was animating the head position with a "trail" effect. This wouldn't need the gcode file, but it would need the head position after every move. In some cases the head position just won't be available, and in the cases that it is there is no guarantee that it would get every position, or even enough, to render anything accurate enough to be useful.
