### ISSUE TITLE
Edit Mode Not Seeing Printer Type List

### ISSUE THREAD

**Issue by jneilliii** [michaelfdeberry/overseer#6]
When editing a printer the type is not shown and the list is not loading in 0.0.4 running on ocotpi.  Saw the same when running on windows.

![image](https://user-images.githubusercontent.com/5249455/42118423-f23799a6-7bd0-11e8-974e-d0b587746b7f.png)

**Comment by michaelfdeberry** [comment]
I believe this is related to the previous issue. Since the connection to Octoprint wasn't successful it left the configuration in an invalid state.

**Comment by jneilliii** [comment]
This issue is resolved with 0.0.5.
