### ISSUE TITLE
Overseer fails to connect to devices running Octoprint 1.3.9

### ISSUE THREAD

**Issue by tophattwaffle** [michaelfdeberry/overseer#8]
![image](https://user-images.githubusercontent.com/6774125/43805638-2855c734-9a66-11e8-8c7c-b998672446fa.png)
In the screenshot there are 4 machines. The Ender 3 machine is powered down, and is showing correctly. The other 3 machines are sitting at the "connecting" status forever. This happens on Octoprint 1.3.9

Restarting Overseer, and octoprint does not have any impact. Webcam viewing still works great though.

**Comment by michaelfdeberry** [comment]
I tested with the latest release and 1.3.9 worked fine for me. Do you know what version of overseer you are running? Also, can you post the overseer.log file, or at least any relevant error messages from it? 

However, your issue may not be Octoprint related at all. If the status is stuck on "Connecting" either the browser can't connect to the overseer back end, or one of the printers is timing out and the status update isn't being pushed to the client. 

If the Ender 3 is powered off, is the Octoprint instance for that printer offline as well? 

If so, what is likely happening is Overseer is trying to connect to the Ender 3, but it's taking longer for the connection to time out then whatever your configured poll interval is. If this what's happening then disabling monitoring for the Ender 3 should get things working for you.

Very contextual print on the CR10 :-)

**Comment by tophattwaffle** [comment]
You are 100% correct. The ender 3 octoprint instance is offline. (Just moved. Not everything is setup yet.)

Disabling monitoring on the Ender 3 and reloading the page resolved the issue.
